from config import Settings
from schemas.modules import ModuleEntry, ModulesConfig
from services.gateway import render_caddyfile

MODULES = ModulesConfig(modules=[
    ModuleEntry(name="apollo", title="Apollo", port=8001),
    ModuleEntry(name="pluto", title="Pluto", port=8004, enabled=False),
])

EXPECTED = """\
# Generated by `make gateway-config` from modules.yaml — do not edit.
{
\tadmin localhost:2019
}

:8000 {
\tredir /apollo /apollo/ 308
\thandle_path /apollo/* {
\t\treverse_proxy localhost:8001
\t}
\t@pluto path /pluto /pluto/*
\thandle @pluto {
\t\trespond "Pluto is not available on this server." 503
\t}
\thandle {
\t\treverse_proxy localhost:8010
\t}
}
"""


def test_render_caddyfile():
    assert render_caddyfile(MODULES, Settings(_env_file=None, PORT=8010, GATEWAY_PORT=8000)) == EXPECTED


def test_render_caddyfile_honours_ports():
    out = render_caddyfile(ModulesConfig(), Settings(_env_file=None, PORT=9010, GATEWAY_PORT=9000))
    assert ":9000 {" in out
    assert "reverse_proxy localhost:9010" in out
