from schemas.modules import ModuleEntry, ModulesConfig
from services.systemd import render_partof_dropin, render_target


def test_render_target_wants_pantheon_and_enabled_modules_only():
    modules = ModulesConfig(modules=[
        ModuleEntry(name="apollo", title="Apollo", port=8001),
        ModuleEntry(name="pluto", title="Pluto", port=8004, enabled=False),
    ])
    assert render_target(modules) == (
        "# Generated by `make service-install-all` from modules.yaml — do not edit.\n"
        "[Unit]\n"
        "Description=Pantheon — gateway, home screen and every enabled module\n"
        "Wants=pantheon.service pantheon-gateway.service apollo.service\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def test_render_partof_dropin():
    assert render_partof_dropin() == (
        "# Generated by Pantheon — stop/restart this module with pantheon.target.\n"
        "[Unit]\n"
        "PartOf=pantheon.target\n"
    )
