"""Render the Caddy gateway config from the module registry.

Each enabled module is proxied under /<name>/ with the prefix stripped, so
the module sees the same paths it serves standalone. /<name> (no slash)
redirects to /<name>/ so the module's relative URLs resolve. Disabled
modules get a 503 notice instead of a proxy error; everything else goes to
Pantheon's own app.
"""

from __future__ import annotations

from config import Settings
from schemas.modules import ModulesConfig


def render_caddyfile(modules: ModulesConfig, settings: Settings) -> str:
    lines = [
        "# Generated by `make gateway-config` from modules.yaml — do not edit.",
        "{",
        "\tadmin localhost:2019",
        "}",
        "",
        f":{settings.GATEWAY_PORT} {{",
    ]
    for m in modules.modules:
        if m.enabled:
            lines += [
                f"\tredir /{m.name} /{m.name}/ 308",
                f"\thandle_path /{m.name}/* {{",
                f"\t\treverse_proxy localhost:{m.port}",
                "\t}",
            ]
        else:
            lines += [
                f"\thandle /{m.name}* {{",
                f'\t\trespond "{m.title} is not available on this server." 503',
                "\t}",
            ]
    lines += [
        "\thandle {",
        f"\t\treverse_proxy localhost:{settings.PORT}",
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)
