"""Render the Caddy gateway config from the module registry.

Each enabled module is proxied under /<name>/ with the prefix stripped, so
the module sees the same paths it serves standalone. /<name> (no slash)
redirects to /<name>/ so the module's relative URLs resolve. Disabled
modules get a 503 notice instead of a proxy error; everything else goes to
Pantheon's own app. Every request is logged as JSON to `settings.access_log_path` for the
status screen.
"""

from __future__ import annotations

from config import Settings
from schemas.modules import ModulesConfig


def render_caddyfile(modules: ModulesConfig, settings: Settings) -> str:
    lines = [
        "# Generated by `make gateway-config` from modules.yaml — do not edit.",
        "{",
        "\tadmin localhost:2019",
        "}",
        "",
        f":{settings.GATEWAY_PORT} {{",
        # JSON access log for services/access_log.py (tmpfs by default).
        "\tlog {",
        f"\t\toutput file {settings.access_log_path} {{",
        "\t\t\troll_size 5MiB",
        "\t\t\troll_keep 1",
        "\t\t}",
        "\t\tformat json",
        "\t}",
    ]
    for m in modules.modules:
        if m.enabled:
            lines += [
                f"\tredir /{m.name} /{m.name}/ 308",
                f"\thandle_path /{m.name}/* {{",
                f"\t\treverse_proxy localhost:{m.port}",
                "\t}",
            ]
        else:
            lines += [
                f"\t@{m.name} path /{m.name} /{m.name}/*",
                f"\thandle @{m.name} {{",
                f'\t\trespond "{m.title} is not available on this server." 503',
                "\t}",
            ]
    lines += [
        "\thandle {",
        f"\t\treverse_proxy localhost:{settings.PORT}",
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)
