"""Render pantheon.target and the per-module drop-in that joins it.

The target Wants= every Pantheon unit, so starting it starts everything; the
drop-in adds PartOf=pantheon.target to a module's own unit (left untouched),
so stopping or restarting the target reaches the module too. A module can
still be restarted on its own.
"""

from __future__ import annotations

from schemas.modules import ModulesConfig

PANTHEON_UNITS = ("pantheon.service", "pantheon-gateway.service")


def render_target(modules: ModulesConfig) -> str:
    units = [*PANTHEON_UNITS, *(m.unit for m in modules.enabled)]
    return (
        "# Generated by `make service-install-all` from modules.yaml — do not edit.\n"
        "[Unit]\n"
        "Description=Pantheon — gateway, home screen and every enabled module\n"
        f"Wants={' '.join(units)}\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def render_partof_dropin() -> str:
    return (
        "# Generated by Pantheon — stop/restart this module with pantheon.target.\n"
        "[Unit]\n"
        "PartOf=pantheon.target\n"
    )
